name: "[ARM64] Build & Push Orchestrator Images"
run-name: "[ARM64] ${{ github.event.head_commit.message }}"

on:
  push:
    branches: [main]

permissions:
  actions: read
  contents: read

jobs:
  build-arm64:
    uses: ./.github/workflows/build-images.yml
    with:
      image_family: arm64
    secrets: inherit
