name: "[AMD64] Build & Push Orchestrator Images"
run-name: "[AMD64] ${{ github.event.head_commit.message }}"

on:
  push:
    branches: [main]

permissions:
  actions: read
  contents: read

jobs:
  build-amd64:
    uses: ./.github/workflows/build-images.yml
    with:
      image_family: amd64
    secrets: inherit
